In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/cleaned_fraud_data.csv')

In [3]:
df.head()

,isFraud,TransactionDT,TransactionAmt,ProductCD,card1,card2,card3,card4,card5,card6,...,id_20,id_28,id_29,id_31,id_35,id_36,id_37,id_38,DeviceType,DeviceInfo
0,0,86400,68.5,W,13926,375.0,150.0,discover,142.0,credit,...,391.0,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown
1,0,86401,29.0,W,2755,404.0,150.0,mastercard,102.0,credit,...,391.0,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown
2,0,86469,59.0,W,4663,490.0,150.0,visa,166.0,debit,...,391.0,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown
3,0,86499,50.0,W,18132,567.0,150.0,mastercard,117.0,debit,...,391.0,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown
4,0,86506,50.0,H,4497,514.0,150.0,mastercard,102.0,credit,...,144.0,New,NotFound,samsung browser 6.2,T,F,T,T,mobile,SAMSUNG SM-G892A Build/NRD90M

In [4]:
## separate target column

X = df.drop('isFraud', axis=1)

In [5]:
y = df['isFraud']

In [ ]:
X.head()

,TransactionDT,TransactionAmt,ProductCD,card1,card2,card3,card4,card5,card6,addr1,...,id_20,id_28,id_29,id_31,id_35,id_36,id_37,id_38,DeviceType,DeviceInfo
0,86400,68.5,W,13926,375.0,150.0,discover,142.0,credit,315.0,...,391.0,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown
1,86401,29.0,W,2755,404.0,150.0,mastercard,102.0,credit,325.0,...,391.0,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown
2,86469,59.0,W,4663,490.0,150.0,visa,166.0,debit,330.0,...,391.0,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown
3,86499,50.0,W,18132,567.0,150.0,mastercard,117.0,debit,476.0,...,391.0,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown
4,86506,50.0,H,4497,514.0,150.0,mastercard,102.0,credit,420.0,...,144.0,New,NotFound,samsung browser 6.2,T,F,T,T,mobile,SAMSUNG SM-G892A Build/NRD90M

In [7]:
print(X.shape)

(73948, 346)

In [8]:
print(y.value_counts())

isFraud
0    71953
1     1995
Name: count, dtype: int64

In [9]:
X.dtypes

TransactionDT       int64
TransactionAmt    float64
ProductCD          object
card1               int64
card2             float64
                   ...
id_36              object
id_37              object
id_38              object
DeviceType         object
DeviceInfo         object
Length: 346, dtype: object

In [10]:
cat_cols = X.select_dtypes(include=['object'])

In [11]:
num_cols = X.select_dtypes(include=['int64','float64'])

In [12]:
cat_cols.shape

(73948, 21)

In [13]:
num_cols.shape

(73948, 325)

In [14]:
print(X.select_dtypes(include='object').nunique())

ProductCD          5
card4              5
card6              5
P_emaildomain     60
M2                 3
M3                 3
M4                 4
M5                 3
M6                 3
id_12              3
id_15              3
id_16              3
id_28              3
id_29              3
id_31             81
id_35              3
id_36              3
id_37              3
id_38              3
DeviceType         3
DeviceInfo       748
dtype: int64

In [15]:
freq = X['DeviceInfo'].value_counts()
print(freq.head())

DeviceInfo
Unknown        49884
Windows        10109
iOS Device      4534
MacOS           3245
Trident/7.0     1916
Name: count, dtype: int64

In [16]:
X['deviceinfo'] = X['DeviceInfo'].map(freq)
print(X['deviceinfo'].head())

0    49884
1    49884
2    49884
3    49884
4        2
Name: deviceinfo, dtype: int64

In [17]:

print(X.select_dtypes(include='object').columns.tolist())

['ProductCD', 'card4', 'card6', 'P_emaildomain', 'M2', 'M3', 'M4', 'M5', 'M6', 'id_12', 'id_15', 'id_16', 'id_28', 'id_29', 'id_31', 'id_35', 'id_36', 'id_37', 'id_38', 'DeviceType', 'DeviceInfo']

In [18]:
X['id_28'].value_counts()

id_28
Unknown    47141
Found      14986
New        11821
Name: count, dtype: int64

In [38]:

import pandas as pd
df_original = pd.read_csv('/content/drive/MyDrive/cleaned_fraud_data.csv')
print([col for col in ['DeviceInfo', 'id_31', 'P_emaildomain'] if col not in df_original.columns])

[]

In [39]:
X

,TransactionDT,TransactionAmt,ProductCD,card1,card2,card3,card4,card5,card6,addr1,...,id_35,id_36,id_37,id_38,DeviceType,deviceinfo,TransactionAmt_Log,TransactionAmt_decimal,Transaction_hour,Transaction_day
0,-1.758565,-0.286720,0.738576,0.817856,0.041076,-0.274361,-2.425510,-1.446219,-1.417635,0.230558,...,0.690897,0.743145,0.694172,0.695749,-0.689380,0.690385,-0.136019,0.516594,-1.802255,-1.646680
1,-1.758563,-0.477663,0.738576,-1.450373,0.224509,-0.274361,-0.898820,-2.432600,-1.417635,0.330592,...,0.690897,0.743145,0.694172,0.695749,-0.689380,0.690385,-1.056557,-0.714202,-1.802255,-1.646680
2,-1.758414,-0.332643,0.738576,-1.062961,0.768482,-0.274361,0.627869,-0.854390,0.703854,0.380609,...,0.690897,0.743145,0.694172,0.695749,-0.689380,0.690385,-0.297069,-0.714202,-1.802255,-1.646680
3,-1.758348,-0.376149,0.738576,1.671868,1.255527,-0.274361,-0.898820,-2.062707,0.703854,1.841103,...,0.690897,0.743145,0.694172,0.695749,-0.689380,0.690385,-0.475142,-0.714202,-1.802255,-1.646680
4,-1.758333,-0.376149,-1.247227,-1.096667,0.920288,-0.274361,-0.898820,-2.432600,-1.417635,1.280913,...,-0.812869,-1.387601,-0.878711,-0.901954,2.180212,-1.705217,-0.475142,-0.714202,-1.802255,-1.646680
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73943,1.628689,-0.424489,0.738576,-0.080827,-0.300489,-0.274361,0.627869,0.625181,0.703854,1.410957,...,0.690897,0.743145,0.694172,0.695749,-0.689380,0.690385,-0.714285,-0.714202,0.941811,1.571333
73944,1.628709,-0.380983,0.738576,0.567906,0.768482,-0.274361,0.627869,0.625181,0.703854,0.330592,...,0.690897,0.743145,0.694172,0.695749,-0.689380,0.690385,-0.496840,-0.714202,0.941811,1.571333
73945,1.628728,-0.448659,0.738576,-1.737278,0.920288,-0.274361,-0.898820,0.575862,0.703854,0.330592,...,0.690897,0.743145,0.694172,0.695749,-0.689380,0.690385,-0.856786,-0.714202,0.941811,1.571333
73946,1.628741,-0.134449,0.076641,-0.787631,1.356732,-0.274361,0.627869,0.625181,-1.417635,-1.079886,...,-0.812869,-1.387601,-0.878711,-0.901954,0.745416,-1.219825,0.273551,-0.714202,0.941811,1.571333
73947,1.628755,-0.472829,-1.247227,0.858871,-1.255604,-0.274361,-0.898820,0.452564,-1.417635,0.380609,...,-0.812869,-1.387601,-0.878711,-0.901954,0.745416,-1.219825,-1.020629,-0.714202,0.941811,1.571333

In [22]:
X.shape

(73948, 346)

In [41]:
X['TransactionAmt']

0       -0.286720
1       -0.477663
2       -0.332643
3       -0.376149
4       -0.376149
           ...
73943   -0.424489
73944   -0.380983
73945   -0.448659
73946   -0.134449
73947   -0.472829
Name: TransactionAmt, Length: 73948, dtype: float64

In [42]:
print(X['TransactionAmt'].describe())

count    7.394800e+04
mean    -7.398684e-17
std      1.000007e+00
min     -6.164375e-01
25%     -4.087783e-01
50%     -2.652084e-01
75%     -1.359841e-02
max      2.273015e+01
Name: TransactionAmt, dtype: float64

In [43]:
import numpy as np

X['TransactionAmt_Log'] = np.log1p(X['TransactionAmt'])

In [44]:
X['TransactionAmt_decimal'] = X['TransactionAmt'] - X['TransactionAmt'].astype(int)

In [45]:
X.head()

,TransactionDT,TransactionAmt,ProductCD,card1,card2,card3,card4,card5,card6,addr1,...,id_35,id_36,id_37,id_38,DeviceType,deviceinfo,TransactionAmt_Log,TransactionAmt_decimal,Transaction_hour,Transaction_day
0,-1.758565,-0.286720,0.738576,0.817856,0.041076,-0.274361,-2.425510,-1.446219,-1.417635,0.230558,...,0.690897,0.743145,0.694172,0.695749,-0.689380,0.690385,-0.337881,-0.286720,-1.802255,-1.64668
1,-1.758563,-0.477663,0.738576,-1.450373,0.224509,-0.274361,-0.898820,-2.432600,-1.417635,0.330592,...,0.690897,0.743145,0.694172,0.695749,-0.689380,0.690385,-0.649442,-0.477663,-1.802255,-1.64668
2,-1.758414,-0.332643,0.738576,-1.062961,0.768482,-0.274361,0.627869,-0.854390,0.703854,0.380609,...,0.690897,0.743145,0.694172,0.695749,-0.689380,0.690385,-0.404430,-0.332643,-1.802255,-1.64668
3,-1.758348,-0.376149,0.738576,1.671868,1.255527,-0.274361,-0.898820,-2.062707,0.703854,1.841103,...,0.690897,0.743145,0.694172,0.695749,-0.689380,0.690385,-0.471843,-0.376149,-1.802255,-1.64668
4,-1.758333,-0.376149,-1.247227,-1.096667,0.920288,-0.274361,-0.898820,-2.432600,-1.417635,1.280913,...,-0.812869,-1.387601,-0.878711,-0.901954,2.180212,-1.705217,-0.471843,-0.376149,-1.802255,-1.64668

In [46]:
# Time features
X['Transaction_hour'] = X['TransactionDT']% 86400 // 3600
X['Transaction_day'] = X['TransactionDT'] // 86400

In [29]:
X

,TransactionDT,TransactionAmt,ProductCD,card1,card2,card3,card4,card5,card6,addr1,...,id_35,id_36,id_37,id_38,DeviceType,deviceinfo,TransactionAmt_Log,TransactionAmt_decimal,Transaction_hour,Transaction_day
0,86400,68.5,4,13926,375.0,150.0,2,142.0,2,315.0,...,2,2,2,2,0,49884,4.241327,0.5,0,1
1,86401,29.0,4,2755,404.0,150.0,3,102.0,2,325.0,...,2,2,2,2,0,49884,3.401197,0.0,0,1
2,86469,59.0,4,4663,490.0,150.0,4,166.0,3,330.0,...,2,2,2,2,0,49884,4.094345,0.0,0,1
3,86499,50.0,4,18132,567.0,150.0,3,117.0,3,476.0,...,2,2,2,2,0,49884,3.931826,0.0,0,1
4,86506,50.0,1,4497,514.0,150.0,3,102.0,2,420.0,...,1,0,1,1,2,2,3.931826,0.0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73943,1633205,40.0,4,9500,321.0,150.0,4,226.0,3,433.0,...,2,2,2,2,0,49884,3.713572,0.0,21,18
73944,1633214,49.0,4,12695,490.0,150.0,4,226.0,3,325.0,...,2,2,2,2,0,49884,3.912023,0.0,21,18
73945,1633223,35.0,4,1342,514.0,150.0,3,224.0,3,325.0,...,2,2,2,2,0,49884,3.583519,0.0,21,18
73946,1633229,100.0,3,6019,583.0,150.0,4,226.0,2,184.0,...,1,0,1,1,1,10109,4.615121,0.0,21,18
73947,1633235,30.0,1,14128,170.0,150.0,3,219.0,2,330.0,...,1,0,1,1,1,10109,3.433987,0.0,21,18

In [30]:
from sklearn.preprocessing import StandardScaler

# Numerical columns
num_cols = X.select_dtypes(include=['int64', 'float64']).columns


scaler = StandardScaler()
X[num_cols] = scaler.fit_transform(X[num_cols])

In [31]:
X

,TransactionDT,TransactionAmt,ProductCD,card1,card2,card3,card4,card5,card6,addr1,...,id_35,id_36,id_37,id_38,DeviceType,deviceinfo,TransactionAmt_Log,TransactionAmt_decimal,Transaction_hour,Transaction_day
0,-1.758565,-0.286720,0.738576,0.817856,0.041076,-0.274361,-2.425510,-1.446219,-1.417635,0.230558,...,0.690897,0.743145,0.694172,0.695749,-0.689380,0.690385,-0.136019,0.516594,-1.802255,-1.646680
1,-1.758563,-0.477663,0.738576,-1.450373,0.224509,-0.274361,-0.898820,-2.432600,-1.417635,0.330592,...,0.690897,0.743145,0.694172,0.695749,-0.689380,0.690385,-1.056557,-0.714202,-1.802255,-1.646680
2,-1.758414,-0.332643,0.738576,-1.062961,0.768482,-0.274361,0.627869,-0.854390,0.703854,0.380609,...,0.690897,0.743145,0.694172,0.695749,-0.689380,0.690385,-0.297069,-0.714202,-1.802255,-1.646680
3,-1.758348,-0.376149,0.738576,1.671868,1.255527,-0.274361,-0.898820,-2.062707,0.703854,1.841103,...,0.690897,0.743145,0.694172,0.695749,-0.689380,0.690385,-0.475142,-0.714202,-1.802255,-1.646680
4,-1.758333,-0.376149,-1.247227,-1.096667,0.920288,-0.274361,-0.898820,-2.432600,-1.417635,1.280913,...,-0.812869,-1.387601,-0.878711,-0.901954,2.180212,-1.705217,-0.475142,-0.714202,-1.802255,-1.646680
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73943,1.628689,-0.424489,0.738576,-0.080827,-0.300489,-0.274361,0.627869,0.625181,0.703854,1.410957,...,0.690897,0.743145,0.694172,0.695749,-0.689380,0.690385,-0.714285,-0.714202,0.941811,1.571333
73944,1.628709,-0.380983,0.738576,0.567906,0.768482,-0.274361,0.627869,0.625181,0.703854,0.330592,...,0.690897,0.743145,0.694172,0.695749,-0.689380,0.690385,-0.496840,-0.714202,0.941811,1.571333
73945,1.628728,-0.448659,0.738576,-1.737278,0.920288,-0.274361,-0.898820,0.575862,0.703854,0.330592,...,0.690897,0.743145,0.694172,0.695749,-0.689380,0.690385,-0.856786,-0.714202,0.941811,1.571333
73946,1.628741,-0.134449,0.076641,-0.787631,1.356732,-0.274361,0.627869,0.625181,-1.417635,-1.079886,...,-0.812869,-1.387601,-0.878711,-0.901954,0.745416,-1.219825,0.273551,-0.714202,0.941811,1.571333
73947,1.628755,-0.472829,-1.247227,0.858871,-1.255604,-0.274361,-0.898820,0.452564,-1.417635,0.380609,...,-0.812869,-1.387601,-0.878711,-0.901954,0.745416,-1.219825,-1.020629,-0.714202,0.941811,1.571333

In [32]:
from imblearn.over_sampling import SMOTE
smote = SMOTE(random_state=42)
X_resampled, y_resampled = smote.fit_resample(X, y)

print('Before SMOTE' ,y.value_counts())

print('After SMOTE' , y_resampled.value_counts())

Before SMOTE isFraud
0    71953
1     1995
Name: count, dtype: int64
After SMOTE isFraud
0    71953
1    71953
Name: count, dtype: int64

In [33]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=100, random_state=42)
rf.fit(X_resampled , y_resampled)

importance = pd.Series(rf.feature_importances_, index=X.columns)
print("Top 10 Features:")
print(importance.nlargest(10))

Top 10 Features:
C13               0.035813
C14               0.034889
card6             0.026412
C4                0.022119
V294              0.019611
TransactionAmt    0.016714
C2                0.016677
P_emaildomain     0.016663
C11               0.015959
V102              0.015539
dtype: float64

In [34]:
top_50 = importance.nlargest(50).index
X_selected = X_resampled[top_50]
y_selected = y_resampled

print( X_resampled.shape)
print( X_selected.shape)

(143906, 350)
(143906, 50)

In [35]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [50]:
import pandas as pd
import pickle

# Original cleaned data load karo
df_orig = pd.read_csv('/content/drive/MyDrive/cleaned_fraud_data.csv')

# Freq maps - original strings se
freq_maps = {}
for col in ['DeviceInfo', 'id_31', 'P_emaildomain']:
    freq_maps[col] = df_orig[col].value_counts().to_dict()

pickle.dump(freq_maps, open('/content/drive/MyDrive/freq_maps.pkl', 'wb'))
print("freq_maps saved!")

# Scaler save karo
pickle.dump(scaler, open('/content/drive/MyDrive/scaler.pkl', 'wb'))
print("scaler saved!")

# Feature columns order save karo
pickle.dump(list(X.columns), open('/content/drive/MyDrive/feature_columns.pkl', 'wb'))
print("feature_columns saved!")

print("Sab done!")

freq_maps saved!
scaler saved!
feature_columns saved!
Sab done!

In [49]:
import pandas as pd
import pickle

# Original cleaned data load karo
df_orig = pd.read_csv('/content/drive/MyDrive/cleaned_fraud_data.csv')

# Check karo kaun se columns hain
print(df_orig.columns[df_orig.columns.str.contains('email|id_31|Device')].tolist())

['P_emaildomain', 'id_31', 'DeviceType', 'DeviceInfo']