In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/cleaned_fraud_data.csv')

In [4]:
df.head()

,isFraud,TransactionDT,TransactionAmt,ProductCD,card1,card2,card3,card4,card5,card6,...,id_20,id_28,id_29,id_31,id_35,id_36,id_37,id_38,DeviceType,DeviceInfo
0,0,86400,68.5,W,13926,375.0,150.0,discover,142.0,credit,...,391.0,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown
1,0,86401,29.0,W,2755,404.0,150.0,mastercard,102.0,credit,...,391.0,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown
2,0,86469,59.0,W,4663,490.0,150.0,visa,166.0,debit,...,391.0,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown
3,0,86499,50.0,W,18132,567.0,150.0,mastercard,117.0,debit,...,391.0,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown
4,0,86506,50.0,H,4497,514.0,150.0,mastercard,102.0,credit,...,144.0,New,NotFound,samsung browser 6.2,T,F,T,T,mobile,SAMSUNG SM-G892A Build/NRD90M

In [5]:
## separate target column

X = df.drop('isFraud', axis=1)

In [6]:
y = df['isFraud']

In [30]:
X.head()

,TransactionDT,TransactionAmt,ProductCD,card1,card2,card3,card4,card5,card6,addr1,...,id_20,id_28,id_29,id_31,id_35,id_36,id_37,id_38,DeviceType,DeviceInfo
0,86400,68.5,W,13926,375.0,150.0,discover,142.0,credit,315.0,...,391.0,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown
1,86401,29.0,W,2755,404.0,150.0,mastercard,102.0,credit,325.0,...,391.0,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown
2,86469,59.0,W,4663,490.0,150.0,visa,166.0,debit,330.0,...,391.0,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown
3,86499,50.0,W,18132,567.0,150.0,mastercard,117.0,debit,476.0,...,391.0,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown
4,86506,50.0,H,4497,514.0,150.0,mastercard,102.0,credit,420.0,...,144.0,New,NotFound,samsung browser 6.2,T,F,T,T,mobile,SAMSUNG SM-G892A Build/NRD90M

In [22]:
list(cat_cols)

['ProductCD',
 'card4',
 'card6',
 'P_emaildomain',
 'M2',
 'M3',
 'M4',
 'M5',
 'M6',
 'id_12',
 'id_15',
 'id_16',
 'id_28',
 'id_29',
 'id_31',
 'id_35',
 'id_36',
 'id_37',
 'id_38',
 'DeviceType',
 'DeviceInfo']

In [8]:
print(X.shape)

(73948, 346)

In [12]:
print(y.value_counts())

isFraud
0    71953
1     1995
Name: count, dtype: int64

In [13]:
X.dtypes

TransactionDT       int64
TransactionAmt    float64
ProductCD          object
card1               int64
card2             float64
                   ...
id_36              object
id_37              object
id_38              object
DeviceType         object
DeviceInfo         object
Length: 346, dtype: object

In [16]:
cat_cols = X.select_dtypes(include=['object'])

In [17]:
num_cols = X.select_dtypes(include=['int64','float64'])

In [18]:
cat_cols.shape

(73948, 21)

In [19]:
num_cols.shape

(73948, 325)

In [40]:
print(X.select_dtypes(include='object').nunique())

ProductCD     5
card4         5
card6         5
M2            3
M3            3
M4            4
M5            3
M6            3
id_12         3
id_15         3
id_16         3
id_28         3
id_29         3
id_35         3
id_36         3
id_37         3
id_38         3
DeviceType    3
dtype: int64

In [41]:
freq = X['DeviceInfo'].value_counts()
print(freq.head())

DeviceInfo
49884    49884
10109    10109
4534      4534
3245      3245
1916      1916
Name: count, dtype: int64

In [42]:
X['deviceinfo'] = X['DeviceInfo'].map(freq)
print(X['deviceinfo'].head())

0    49884
1    49884
2    49884
3    49884
4      264
Name: deviceinfo, dtype: int64

In [43]:

print(X.select_dtypes(include='object').columns.tolist())

['ProductCD', 'card4', 'card6', 'M2', 'M3', 'M4', 'M5', 'M6', 'id_12', 'id_15', 'id_16', 'id_28', 'id_29', 'id_35', 'id_36', 'id_37', 'id_38', 'DeviceType']

In [34]:
X['id_28'].value_counts()

id_28
Unknown    47141
Found      14986
New        11821
Name: count, dtype: int64

In [45]:
from sklearn.preprocessing import LabelEncoder
## high cardinality cols
high_card_cols = ['DeviceInfo', 'id_31', 'P_emaildomain']
for col in high_card_cols:
    freq = X[col].value_counts()
    X[col] = X[col].map(freq)

## Categorical features encoding
le = LabelEncoder()
cat_cols = X.select_dtypes(include=['object']).columns
for col in cat_cols:
    X[col] = le.fit_transform(X[col].astype(str))

In [50]:
X

,TransactionDT,TransactionAmt,ProductCD,card1,card2,card3,card4,card5,card6,addr1,...,id_20,id_28,id_29,id_31,id_35,id_36,id_37,id_38,DeviceType,deviceinfo
0,86400,68.5,4,13926,375.0,150.0,2,142.0,2,315.0,...,391.0,2,2,47177,2,2,2,2,0,49884
1,86401,29.0,4,2755,404.0,150.0,3,102.0,2,325.0,...,391.0,2,2,47177,2,2,2,2,0,49884
2,86469,59.0,4,4663,490.0,150.0,4,166.0,3,330.0,...,391.0,2,2,47177,2,2,2,2,0,49884
3,86499,50.0,4,18132,567.0,150.0,3,117.0,3,476.0,...,391.0,2,2,47177,2,2,2,2,0,49884
4,86506,50.0,1,4497,514.0,150.0,3,102.0,2,420.0,...,144.0,1,1,226,1,0,1,1,2,264
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73943,1633205,40.0,4,9500,321.0,150.0,4,226.0,3,433.0,...,391.0,2,2,47177,2,2,2,2,0,49884
73944,1633214,49.0,4,12695,490.0,150.0,4,226.0,3,325.0,...,391.0,2,2,47177,2,2,2,2,0,49884
73945,1633223,35.0,4,1342,514.0,150.0,3,224.0,3,325.0,...,391.0,2,2,47177,2,2,2,2,0,49884
73946,1633229,100.0,3,6019,583.0,150.0,4,226.0,2,184.0,...,368.0,1,1,1371,1,0,1,1,1,10109
73947,1633235,30.0,1,14128,170.0,150.0,3,219.0,2,330.0,...,533.0,0,0,3542,1,0,1,1,1,10109

In [48]:
X.drop('DeviceInfo' , axis=1 , inplace=True)

In [49]:
X.shape

(73948, 346)

In [53]:
X['TransactionAmt']

0         68.5
1         29.0
2         59.0
3         50.0
4         50.0
         ...
73943     40.0
73944     49.0
73945     35.0
73946    100.0
73947     30.0
Name: TransactionAmt, Length: 73948, dtype: float64

In [55]:
print(X['TransactionAmt'].describe())

count    73948.000000
mean       127.813073
std        206.869199
min          0.292000
25%         43.250000
50%         72.950000
75%        125.000000
max       4829.950000
Name: TransactionAmt, dtype: float64

In [58]:
import numpy as np

X['TransactionAmt_Log'] = np.log1p(X['TransactionAmt'])

In [56]:
X['TransactionAmt_decimal'] = X['TransactionAmt'] - X['TransactionAmt'].astype(int)

In [59]:
X.head()

,TransactionDT,TransactionAmt,ProductCD,card1,card2,card3,card4,card5,card6,addr1,...,id_29,id_31,id_35,id_36,id_37,id_38,DeviceType,deviceinfo,TransactionAmt_decimal,TransactionAmt_Log
0,86400,68.5,4,13926,375.0,150.0,2,142.0,2,315.0,...,2,47177,2,2,2,2,0,49884,0.5,4.241327
1,86401,29.0,4,2755,404.0,150.0,3,102.0,2,325.0,...,2,47177,2,2,2,2,0,49884,0.0,3.401197
2,86469,59.0,4,4663,490.0,150.0,4,166.0,3,330.0,...,2,47177,2,2,2,2,0,49884,0.0,4.094345
3,86499,50.0,4,18132,567.0,150.0,3,117.0,3,476.0,...,2,47177,2,2,2,2,0,49884,0.0,3.931826
4,86506,50.0,1,4497,514.0,150.0,3,102.0,2,420.0,...,1,226,1,0,1,1,2,264,0.0,3.931826

In [61]:
# Time features
X['Transaction_hour'] = X['TransactionDT']% 86400 // 3600
X['Transaction_day'] = X['TransactionDT'] // 86400

In [62]:
X

,TransactionDT,TransactionAmt,ProductCD,card1,card2,card3,card4,card5,card6,addr1,...,id_35,id_36,id_37,id_38,DeviceType,deviceinfo,TransactionAmt_decimal,TransactionAmt_Log,Transaction_hour,Transaction_day
0,86400,68.5,4,13926,375.0,150.0,2,142.0,2,315.0,...,2,2,2,2,0,49884,0.5,4.241327,0,1
1,86401,29.0,4,2755,404.0,150.0,3,102.0,2,325.0,...,2,2,2,2,0,49884,0.0,3.401197,0,1
2,86469,59.0,4,4663,490.0,150.0,4,166.0,3,330.0,...,2,2,2,2,0,49884,0.0,4.094345,0,1
3,86499,50.0,4,18132,567.0,150.0,3,117.0,3,476.0,...,2,2,2,2,0,49884,0.0,3.931826,0,1
4,86506,50.0,1,4497,514.0,150.0,3,102.0,2,420.0,...,1,0,1,1,2,264,0.0,3.931826,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73943,1633205,40.0,4,9500,321.0,150.0,4,226.0,3,433.0,...,2,2,2,2,0,49884,0.0,3.713572,21,18
73944,1633214,49.0,4,12695,490.0,150.0,4,226.0,3,325.0,...,2,2,2,2,0,49884,0.0,3.912023,21,18
73945,1633223,35.0,4,1342,514.0,150.0,3,224.0,3,325.0,...,2,2,2,2,0,49884,0.0,3.583519,21,18
73946,1633229,100.0,3,6019,583.0,150.0,4,226.0,2,184.0,...,1,0,1,1,1,10109,0.0,4.615121,21,18
73947,1633235,30.0,1,14128,170.0,150.0,3,219.0,2,330.0,...,1,0,1,1,1,10109,0.0,3.433987,21,18

In [67]:
from sklearn.preprocessing import StandardScaler

# Numerical columns
num_cols = X.select_dtypes(include=['int64', 'float64']).columns


scaler = StandardScaler()
X[num_cols] = scaler.fit_transform(X[num_cols])

In [68]:
X

,TransactionDT,TransactionAmt,ProductCD,card1,card2,card3,card4,card5,card6,addr1,...,id_35,id_36,id_37,id_38,DeviceType,deviceinfo,TransactionAmt_decimal,TransactionAmt_Log,Transaction_hour,Transaction_day
0,-1.758565,-0.286720,0.738576,0.817856,0.041076,-0.274361,-2.425510,-1.446219,-1.417635,0.230558,...,0.690897,0.743145,0.694172,0.695749,-0.689380,0.690430,0.516594,-0.136019,-1.802255,-1.646680
1,-1.758563,-0.477663,0.738576,-1.450373,0.224509,-0.274361,-0.898820,-2.432600,-1.417635,0.330592,...,0.690897,0.743145,0.694172,0.695749,-0.689380,0.690430,-0.714202,-1.056557,-1.802255,-1.646680
2,-1.758414,-0.332643,0.738576,-1.062961,0.768482,-0.274361,0.627869,-0.854390,0.703854,0.380609,...,0.690897,0.743145,0.694172,0.695749,-0.689380,0.690430,-0.714202,-0.297069,-1.802255,-1.646680
3,-1.758348,-0.376149,0.738576,1.671868,1.255527,-0.274361,-0.898820,-2.062707,0.703854,1.841103,...,0.690897,0.743145,0.694172,0.695749,-0.689380,0.690430,-0.714202,-0.475142,-1.802255,-1.646680
4,-1.758333,-0.376149,-1.247227,-1.096667,0.920288,-0.274361,-0.898820,-2.432600,-1.417635,1.280913,...,-0.812869,-1.387601,-0.878711,-0.901954,2.180212,-1.693643,-0.714202,-0.475142,-1.802255,-1.646680
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73943,1.628689,-0.424489,0.738576,-0.080827,-0.300489,-0.274361,0.627869,0.625181,0.703854,1.410957,...,0.690897,0.743145,0.694172,0.695749,-0.689380,0.690430,-0.714202,-0.714285,0.941811,1.571333
73944,1.628709,-0.380983,0.738576,0.567906,0.768482,-0.274361,0.627869,0.625181,0.703854,0.330592,...,0.690897,0.743145,0.694172,0.695749,-0.689380,0.690430,-0.714202,-0.496840,0.941811,1.571333
73945,1.628728,-0.448659,0.738576,-1.737278,0.920288,-0.274361,-0.898820,0.575862,0.703854,0.330592,...,0.690897,0.743145,0.694172,0.695749,-0.689380,0.690430,-0.714202,-0.856786,0.941811,1.571333
73946,1.628741,-0.134449,0.076641,-0.787631,1.356732,-0.274361,0.627869,0.625181,-1.417635,-1.079886,...,-0.812869,-1.387601,-0.878711,-0.901954,0.745416,-1.220624,-0.714202,0.273551,0.941811,1.571333
73947,1.628755,-0.472829,-1.247227,0.858871,-1.255604,-0.274361,-0.898820,0.452564,-1.417635,0.380609,...,-0.812869,-1.387601,-0.878711,-0.901954,0.745416,-1.220624,-0.714202,-1.020629,0.941811,1.571333

In [69]:
from imblearn.over_sampling import SMOTE
smote = SMOTE(random_state=42)
X_resampled, y_resampled = smote.fit_resample(X, y)

print('Before SMOTE' ,y.value_counts())

print('After SMOTE' , y_resampled.value_counts())

Before SMOTE isFraud
0    71953
1     1995
Name: count, dtype: int64
After SMOTE isFraud
0    71953
1    71953
Name: count, dtype: int64

In [71]:
from google.colab import drive
drive.mount('/content/drive')

df.to_csv('/content/drive/MyDrive/fraud_detection_processed.csv', index=False)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).